export const PRIMARY_CATEGORIES = [
  { value: "ai-apps-and-agents", label: "AI Apps and Agents" },
  { value: "ITandAdministration", label: "IT and Administration" },
  { value: "analytics", label: "Analytics" },
  { value: "blockchain", label: "Blockchain" },
  { value: "Collaboration", label: "Collaboration" },
  { value: "Commerce", label: "Commerce" },
  { value: "compliance", label: "Compliance" },
  { value: "CustomerService", label: "Customer Service" },
  { value: "databases-saas", label: "Databases SaaS" },
  { value: "developer-tools-saas", label: "Developer Tools SaaS" },
  { value: "devops", label: "DevOps" },
  { value: "Finance", label: "Finance" },
  { value: "geolocation", label: "Geolocation" },
  { value: "HumanResources", label: "Human Resources" },
  { value: "identity", label: "Identity" },
  { value: "compute-saas", label: "Compute SaaS" },
  { value: "integration", label: "Integration" },
  { value: "IoT", label: "IoT" },
  { value: "ArtificialIntelligence", label: "Artificial Intelligence" },
  { value: "Marketing", label: "Marketing" },
  { value: "media", label: "Media" },
  { value: "migration", label: "Migration" },
  { value: "mixed-reality", label: "Mixed Reality" },
  { value: "monitoring-and-diagnostics", label: "Monitoring and Diagnostics" },
  { value: "OperationsSupplyChain", label: "Operations Supply Chain" },
  { value: "Productivity", label: "Productivity" },
  { value: "task-project-management", label: "Task Project Management" },
  { value: "Sales", label: "Sales" },
  { value: "security", label: "Security" },
  { value: "web", label: "Web" },
] as const;

export const CATEGORY_SUBCATEGORIES: Record<string, string[]> = {
  "ai-apps-and-agents": [],
  "ITandAdministration": [],
  "analytics": [],
  "blockchain": [],
  "Collaboration": [],
  "Commerce": [],
  "compliance": [],
  "CustomerService": [],
  "databases-saas": [],
  "developer-tools-saas": [],
  "devops": [],
  "Finance": [],
  "geolocation": [],
  "HumanResources": [],
  "identity": [],
  "compute-saas": [],
  "integration": [],
  "IoT": [],
  "ArtificialIntelligence": [],
  "Marketing": [],
  "media": [],
  "migration": [],
  "mixed-reality": [],
  "monitoring-and-diagnostics": [],
  "OperationsSupplyChain": [],
  "Productivity": [],
  "task-project-management": [],
  "Sales": [],
  "security": [],
  "web": []
};

export const INDUSTRIES = [
  "DefenseAndIntelligence",
  "Distribution",
  "Education",
  "Energy",
  "FinancialServices",
  "Government",
  "HealthCareandLifeSciences",
  "HospitalityandTravel",
  "Manufacturing",
  "MediaAndCommunications",
  "OtherPublicSectorIndustries",
  "ProfessionalServices",
  "RetailandConsumerGoods",
  "SustainabilityIndustry"
] as const;

export const MARKETS = [
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "JP", name: "Japan" },
  { code: "IN", name: "India" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  // Add more markets as needed
] as const;
